const englishText = {
  id: "englishText",
  titles: {
    sergi: "Prince Sergey Alexandrovich Romanov",
    ella: "Elizabeth Princess of Hesse",
    og: "The Finger of Og",
    water: "The Water Pits",
    known: "Famous Guests",
  },
  frontPage: `
    End of the 19th century, Jerusalem is awakening from a hibernation period of 400 years and ignites the imagination of Christians worldwide. The Ottoman rule begins to open up to the West and institutes reforms concerning its stance towards Christians and Jews. Priests, historians, writers, artists and pilgrims come to visit the awakening city and share their experiences with their nationals from their respective homeland. The big empires of the time initiate financial investments, found consulates and renovate churches around Palestine. The Russian Empire is the definitive leader in this international arena; Russian representatives are efficient and highly motivated, they forge strong connections, they promote projects and erect constructions all over the Land of Israel.

    The Russian people, who are instilled with the feeling of the Holy Spirit, start awakening and thousands of pilgrims travel all the way from Russia to Palestine. IOPS(Imperial Orthodox Palestine Society), Russian Orthodoxy’s umbrella organization, is founded and begins its activities with zeal. A chain of care is created for every pilgrim since the first moments of their journey, from their village or city in Russia, and to the furthest churches in the Middle East. Here in Jerusalem the majority of the sojourners reside in the hospitable and welcoming hostels that were constructed in the names of the Tsarina Maria Alexandrovna and Elisheva, mother of John the Baptist (Yelizabeta in Russian).

    Sergey’s Courtyard is the apogee of the Russian pilgrims hostels in Jerusalem; Imperial commissioners, such as Dmitry Smyshlyayev, the Archimandrite Antonin Kapustin and others prolong their stay in Palestine and, representing the organization, they embraced the responsibility of ameliorating the living conditions for the thriving pilgrim movement.
    Jerusalem, a city where temperatures can drop below freezing point, poses a dire need for permanent constructions, as numerous pilgrims oftentimes reside in big pavilions and suffer the winter’s wrath in the name of their faith.

    Back in Russia, books of journeys to holy sites for Christianity in the Levant are being published and the general public’s interest of all social groups is growing. Prestigious members of Russia’s high society start planning quests to the Holy Land with the Society’s support. For their sake and the rest of the pilgrims’, the Courtyard was brought to being as the emblem of the IOPS led by Sergey Alexandrovich, brother of Tsar Alexander III and chairman of the Society.

    The hostel in Sergey’s Courtyard can accommodate 418 guests and few selected rooms (25) are appropriated for guests specifically requesting convenience as the style of European hotels dictated at the time.
    
    The plot of land of 4,000 s.m., on which we are currently standing, was purchased next to the church of the Holy Trintity and the old city’s Jaffa Gate and was given the name Sergey’s Courtyard, in the name of Prince Sergey Alexandrovich. The task of the planning and construction was appointed to the Greek architect, George Frankgie. Frangkie was young and relatively inexperienced, but despite that his captivating style built him a great reputation in that era’s Palestine. Leading the operations stands D. Smyshlyayev, a multi-faceted and dexterous man, who enter the construction field for the first time. Frankgie and Smyshlyayev face a serious challenge.
    
    The construction works are initiated in 1886 and the first complication to deal with is the shortage of timber and stone. Smyshlyayev gets exasperated from the high prices of the raw materials in Palestine compared to his homeland Russia, and as a consequence most of the timber is imported from Russia along with a small portion of the stone. The second problem is the quality of the labor force that is mainly comprised of locals, farmers or camel riders. Nevertheless, Smyshlyayev was very insistent and punctual concerning the workers’ fair payment and handled them kindly and politely. In addition, another principal problem was the limited budget that was transferred gradually in installments, in accordance with the correspondence between Saint-Peterburg and Jerusalem.
    
    Furthermore, the architect Frankgie was involved in additional projects, such as the church of Mary Magdalene on the Mount of Olives, Nevsky Courtyard and other projects that were irrelevant to the Society’s activity. Because of the above mentioned complications, coupled with the fact that Frankgie was inexperienced, the famous architect Conrad Schick was appended to the project as a consultant.
    
    The Courtyard was designed to host as many pilgrims as possible and satisfy their basic needs. In addition to the Courtyard, there was a lodging of the highest standards in all Palestine and provided rooms at three different levels.
    C-class rooms were intended for the greater public and were ultimately basic. They contained 20 to 60 beds, while the travelers’ equipment was kept in storerooms on the ground floor of the building and the rooms were designed in such a way that each guest would have a space significantly larger than the times’ standard dormitory size. These rooms were purposed for short-term stays and the pilgrims were hosted in them for a minimal fee.
    B-class rooms contained less beds compared to the rooms for the general public and instead they did include wardrobes and wooden chests for luggage.
    A-class rooms were the most luxurious and were intended for the Courtyard’s prominent guests of high status. These rooms were colorful and included ornamental pictures, mirrors and furniture that was rare to find in the city of Jerusalem of the time; all these objects made their way from Russia to Palestine in order to grant the rooms a sense of comfort and style of a level tantamount to that of grand hotels in Europe.
    Apart from the rooms, supplementary amenities were introduced such as a kitchen, a bakery, dining halls, a water boiler, showers and a laundry facility.
    The overall construction cost of Sergey’s Courtyard stood at 380 thousand francs in 1888 (approximately equal to 2.5 million euros today).
    
    The Society’s (IOPS) administration was located in Sergey’s Courtyard. The site was utilized for signatures in the special passports issued for pilgrims, safekeeping of travelers’ equipment and as a starting point of journeys to holy sites in Palestine, among other functions.
    Pilgrims that chose to get accommodated in Sergey’s Courtyard deposited an amount of one to five rubles for medical services. In addition, they deposited an amount of 5 rubles, which was returned by the time they left the hostel.
    
    Moreover, the Society assumed responsibility of providing food for the pilgrims during their quests in the Holy Land. Dinner and breakfast were served in the public dining hall whose cost for each pilgrim was five kopecks. Bread and kvass (a beer-like drink of trivial alcohol concentration) were distributed for free. Borscht soup and porridge cost three kopecks while boiling water in the morning and night would cost the pilgrim one kopeck only. According to the Society’s testimonies, for every 5 rubles a pilgrim would pay, the Society would pay 20 rubles for accommodation, food and additional needs.
    
    During the beginning of the 20th century Sergey’s Courtyard was a vibrant and lively place, which was the epicenter of pilgrim life during their stay in Jerusalem. Until the outbreak of WWI the site hosted artist workshops, a stable, a firefighter station, a library, a garage, laundry facilities, two dining halls, a bakery, a banquet hall and more. The Courtyard provided a base for and hosted very distinguished guests, professors, soldiers, sailors, priests and ordinary pilgrims.    
`,
  particularInfo: {
    ella: `
            When someone tries to imagine the ultimate princess from the legends, he is probably thinking of a figure that resembles Elizabeth Princess of Hesse, daughter to the German Ducal family of Hesse-Darmstadt on the riverbanks of the Rhine. In southern Germany, a content and bountiful region, life was progressing pleasantly without any lack of either water or food; the main pastime activities of the family were hunting and sitting by the river. Elizabeth is known by her friends and family as “Ella”.
            This dynasty’s origins go back to the Roman Empire, and Ella herself is grand-daughter of the Queen of England of that period, Queen Victoria, and daughter of Ludwig IV Duke of Hesse, as well as great-aunt to Prince Philip, Duke of Edinburgh. 
            
            Even though Ella was born into one of the oldest and most esteemed dynasties in Europe, her family lived relatively modestly and Ella and her siblings received an education based on the values of modesty and courtesy. The children of the ducal family cleaned their rooms themselves and were dressed in clothes sown by their mother Alice. During the days of the Austro-Prussian war Elizabeth and her mother Alice would visit the wounded soldiers in the hospital.
            
            Ella’s beauty was extraordinary and she was considered the most beautiful woman in Europe in that period. She had a lot of admirers and suitors, among which were Wilhelm Prince of Prussia, who ended up being the last Kaizer of the kingdom of Prussia, the Prince Felix Yusupov and the Grand Duke Konstantin, who wrote a poem about her beauty - “Let us all sing praises to the Creator, who gave such beauty to a soul divine”. However, Elizabeth rejects them all. 
            
            In 1878 diphtheria spreads throughout the ducal house and takes Alice, Ella’s mother, and Marie, her youngest sister. Great sorrow surrounded Elizabeth and the otherwise usually content ducal family.
            
            Ella’s aunt, Maria Alexandrovna Empress of Russia, wife of Tsar Alexander II, was a permanent guest of the Hesse family mansion, together with her two young sons, Sergey and Paul. The two boys play with the princesses and get know each other in the way children do. Young Sergey, who was introduced to Ella as a child, becomes Grand Duke of Russia as years go by, he falls in love with her and asks for her hand. Ella rejects his courting and Grand Duke Sergey is compelled to propose marriage more than once in order to win Ella.
            In 1881 Sergey’s father, Tsar Alexander II is assassinated and during the same year Serey’s mother, Maria Alexandrovna, passes away due to a severe illness.
            Ella and Sergey, connected by the grief of loss and by their common faith in Orthodox Christianity, get even closer. Sergey’s second marriage proposal is answered positively.
            Elizabeth Prince of Hesse and by Rhine  becomes Elizabeta Feodorovna Grand Duchess of Russia. Elizabeth, who grew up in a Protestant family, the most common Christian denomination in Germany at the time, decides after few years of marriage to convert to Orthodoxy, the most common Christian denomination in Russia and especially within the royal family circles. Ella’s decision granted her immeasurable sympathy from the Russian people, on one hand, but a sense of alienation from the family she left behind in Germany.
            The highest-ranking priest of the Russian Church, the Metropolite, said in the conversion ceremony what would prove to be a prophecy in retrospect: “As one who chose with her own free will to join the faith, and thus all that comprises Russia’s soul, she has every right to utter the words of Ruth the Moabite “Your people are my people and your God is my God” (Ruth 2:11).
            Sergey and Elizabeth did not bring children to the world; however they fill their hearts caring for all the rest of the children of the royal family. Paul, Sergey’s younger brother, was banished from Russia because of an inappropriate marriage resulting in Paul’s children getting adopted by Sergey and Elizabeth and cared for with great devotion.
            
            In 1888 Elizabeth and Sergey make their way to Palestine for the inauguration of the church of Mary Magdalene on the Mount of Olives that was built in honor of Sergey’s mother, Maria Alexandrovna. They visit the holy sites in the city of Jerusalem and around it and, as faithful Christians, they stay deeply impressed by their journey.
             Sergey and Elizabeth at the inauguration of the church of Mary Magdalene
            
            In 1891, three years following their visit in Palestine, Sergey is nominated Governor of Moscow and Elizabeth displays remarkable care and concern towards the city’s citizens. She is remembered roaming around the city under a fake identity in order to grasp the troubles of the city’s poor. Moreover, she founds aid associations for Moscow’s poor population and also its surrounding towns; she also leads the establishment of the Red Cross in the city. At the same time, more and more voices against the tsarists rule are heard, revolutionary groups attain more power and get to action; in February 1905 Sergey was murdered, as an explosive device was thrown at his carriage outside the Kremlin. Sergey exploded to thousands of pieces and legend has it that his fingers were found on nearby roofs. 
            The day following the assassination, Elizabeth is extremely careful with her appearance out of honor and avoids crying publicly. In the days to come Elizabeth is overflowing in sorrow, and before the funeral service she is found in incessant prayer over Sergey’s coffin and on his tomb she has the following inscription written down: “Father, release them, for they do not know what they have done”.
            The night before Sergey’s burial, Elizabeth reaches the prison in order to visit the Sergey’s assassin. Elizabeth asks for his remorse and in return she would forgive him personally and request for a milder punishment. The assassin denied claiming that the royal family turned him, against his will, into a murderer, and thus he does not regret his deed. Elizabeth asks to spare his life, despite the fact he did not regret his deed, but he is convicted and eventually executed. The vigorous encounter between Elizabeth and the murder of her husband is described in the theatrical play “The Just Assassins” by Albert Camus. 
            Sergey’s assassination drastically changes Elizabeth’s life; she employs the mourning attire, turns vegetarian and gradually distances herself from royal pleasures and delights. Four years later she sells her luxurious jewelry collection, her wedding ring and all her princely possessions. With the capital she raises, she founds the “Saint Martha and Saint Mary Convent” and becomes its abbess. Not a lot of time later, she erected in the complex of the convent a hospital, a pharmacy and an orphanage. Elizabeth and her nuns are constantly working around the clock and provide aid to whoever needs it in Moscow. Over the course of many years she cares and prays for all those who faced fate’s cruel side.
            In 1918, roughly a year after the October revolution and the rise of Bolshevik rule, Lenin orders to arrest the nun, former Princess Elizabeth, together with other family members. Elizabeth is transferred to Yekaterinburg and placed under house arrest there. One of those days they are taken by the Cheka (the general security force of the Bolshevik rule) to an iron mine, around 18 kilometers away from the place they were kept captive. Their captors rob the prisoners’ few remaining valuables and beat them. Firstly, they throw Elizabeth and, after her, all the rest beaten royal family members to a pit in the iron mine 20 meters in depth. In time, one of the murderers narrated that the nobles discarded to the pit survived the fall and sang Christian hymns awaiting their death. The executions commander orders two grenades to be thrown in the pit in order to “finish the job”.
            Three moths later, the White Army forces still partly loyal to the previous regime, reach the iron mine, find the pit and recover the bodies. They discover that the body of Elizabeth and the others were preserved in a decent condition inside the pit. Further, they discover that Elizabeth did not die directly, but had the strength to bandage the head of Prince Ioann with her wimple.
            In 1920 White Army forces transfer the remains to be buried in the Orthodox Christian cemetery in Beijing in order to save them from the Bolsheviks. During the same year, Elizabeth’s remains are moved, as she had always dreamt, to be buried in the church of Mary Magdalene on the Mount of Olives. In 1981 she is canonized as a saint by the Russian Orthodox church as a sign of honor for her good deeds. Her figure is one of the ten saints of the 20th century whose statues decorate the upper part of the front entrance of Westminster Abbey in London.
                    `,
    sergi: `Sergey Alexandrovich Romanov, son of the Romanov dynasty, which ruled the Russian Empire for approximately 300 consecutive years, was born on May 11th 1857 in the Ekaterina palace located in the town of Pushkin, roughly 30 kilometers south of Saint-Petersburg. Sergey was the seventh son out of Tsar Alexander’s II eight children, brother to Tsar Alexander III, uncle and right-hand person to the last Tsar, Nikolai II.

        Sergey is depicted by the family’s acquaintances as quite introverted and shy as a child, reminding his mother in his personality and deeds. Much like his mother, he grew up an ardently observant Christian and his faith was the common denominator for many of the actions over the course of his life.

        As a child, Sergey is deeply interested in art, music and languages. His instructors cultivate his capabilities and Sergey learns a number of languages, specializes in the Italian language and grows extremely fond of Italian culture and art. Later in his life Sergey also met with Russia’s greatest literary composers – Dostoyevsky and Tolstoy.
        
        As a youngster, Sergey tends to frequently travel with his mother to her birthplace, the Grand Duchy of Hesse and by Rhine - today's central Germany; this is where he makes the acquaintance of Elizabeth, Princess of Hesse and by Rhine, who in the future will be his wife.

        As expected by male nobility and with respect to his fastidious nature, Sergey pursues a military career. He is appointed senior officer of an infantry battalion and at his 28th year of age the Russo-Turkic war begins. Sergey takes an active part in the war and his achievements grant him the badge of St. George for commanding officers’ military activity. Sergey will go on climbing up the military hierarchy while he fills various positions; from command of the military’s special forces (Preobrazhensky Regiment), through administrative command of the Emperor’s Guard until the overall command of the military district of Moscow.

        Being a God-fearing Christian, Sergey feels strong bonds to the Holy Land and the holy sites of Christianity in it. He reaches Jerusalem for the first time in June 1881 and sojourns to the holy sites together with his cousin. During these years the various efforts for the foundation of the IOPS get to be fruitful and Sergey accepts to become the first chairman of the Society. IOPS is formally established in 1882 in a festive ceremony led by Sergey.
        As the first chairman of the organization, Sergey grants it prestige and power inside the borders of the Russian Empire. As aforementioned, the impressive building in which we are standing today bears his name.

        Sergey’s life is fraught with tragedies, disasters and wars; in 1880 his mother, Empress Maria Alexandrovna died after a prolonged struggle with a serious disease, and the following year his father Tsar Alexander II was murdered by assassins. The passing of his parents, urge Sergey to strengthen his relationship with his childhood friend Elizabeth, Princess of Hesse. Elizabeth comes from the Grand Duchy of Hesse and by Rhine, as did Sergey’s mother; she is the grand-daughter of Victoria, Queen of England and daughter of Ludwig IV, Grand Duke of Hesse and by Rhine.
        
        In 1878 Eizabeth’s mother and sister die because of the diphtheria epidemic. The sorrow and bereavement draw the Princess and the Prince closer together, who both share the same ardor concerning their Christian faith. Elizabeth chooses Sergey as her future husband over her numerous admirers and seals the bond between her life and the Russian Empire. The imperial wedding took place in the winter palace in Saint-Peterburg in 1884. Sergey and Elizabeth lead a devoted and loving married life but childless, as well. However, they regularly invite the children of other members of the family and when Sergey’s brother, Paul, was banished, they happily adopted his children and raised them with devotion and love.
        Sergey and his wife Elizabeth decide to pursue a journey of pilgrimage to the Holy Land in 1888. There they participate in the consecration of the church of Mary Magdalene in the Mount Of Olives and they visit here, Sergey’s Courtyard, which by that time was in its final construction stages.
        Sergey’s influence in the maneuvering of the Empire broadens, he serves as a consultant to his relatives the Tsars and in 1891 he is appointed Governor of Moscow. 
        
        The mystery shrouding Sergey’s life gets even greater during his term as the Governor of Moscow; the child that loved art and grew up to pursue a successful and glorious military career now bears the responsibility for the entire capital city of the Empire.
        
        On one hand, Sergey and his wife are known for their concern about their fellow nationals. They roam the city under false identities in order to comprehend the troubles of the simple folk. Additionally, Sergey is head of a number of philanthropic organizations such as the Social Care Society in Moscow, the Education Advancement for Blind Children Society, the Social Society for the Homeless, the Neglected Children & Adolescents Society and many more. He erects student dormitories, fights corruption and crime, while he could easily disappear in his position without anyone saying a word.
        
        On the other hand, Sergey lived in one of the most turbulent periods in  Russia’s history and enters the position of Governor of Moscow during the expulsion of the city’s 25 thousand Jews (a decision made before his appointment). Moreover, Sergey is the capital’s governor at the time of the Khodynka tragedy that occurred during the coronation of Tsar Nikolai II, in which approximately 1,300 residents of Moscow were trampled to death and many more injured.
        It is difficult to overview the importance of this period when incidents like this arise. Irrespective of his involvement and responsibility concerning the aforementioned incident, Sergey decides to quit all his governmental roles and positions in 1905, arguing that “new times require new faces”.
        
        Just a little time after his retirement Sergey was assassinated when a molotov cocktail was thrown inside his carriage in February 1905.        
        `,
    water: `Since Jerusalem’s early days, almost 4,000 years ago, water always constituted a principal complication. On one hand, Jerusalem’s strategic location on top of the mountain provides defence from invaders, but on the other hand, makes it difficult to provide the city with continuous supply of water.

        The great importance of water in the city was apparently the reason for which, during the days of the Temple, a special water festival was prepared every year in Jerusalem during the Sukkot holiday (Feast of Tabernacles) that was called Simchat Beit Ha-Shoeva (Rejoicing of the Water-Drawing House). The festival was accompanied by various popular rituals: The people of the tribe of Levi pumped water from the Gikhon spring and brought it all the way up to the altar in the Temple, the people expressed their gratitude and praised God for all the rainfall of the passing year and prayed for another year blessed with bountiful rain. 
        Based on this festival, the sages of Israel said: “He who has not witnessed Simchat Beit Ha-Shoeva, has not witnessed rejoicing in his days at all”.

        In the past Jerusalem had two main springs – the Gikhon spring and Ein Rogel (Joab’s Well). The Gikhon spring supplies the city with water for thousands of years, and even to this day, although its water supply is not systematic. Ein Rogel had been gradually drying up over the years till the beginning of the 20th century, when it was found completely dry.

        The permanent solution for the city’s water supply came with the introduction of two long aqueducts (10 kilometers), one built by the Hashmonean dynasty and the other by the Romans. Both aqueducts comprised the city’s water supply system for hundreds of years. In periods that the rulers of Jerusalem were out of resources or suffered from war or sieges, the city’s water supply was interrupted or even entirely blocked, owing to the fact that the aqueducts required regular maintenance and the respective resource allocation.
        The city residents, then, turned to the solution of rainwater harvesting in pools and water pits. The water collected in the pools was used for cleaning and irrigation, as it was stagnant for long periods during the summer months; the water pits provided clean potable water.

        By the end of the 19th and the beginning of the 20th century, the number of pilgrims arriving to Jerusalem and the Holy Land fluctuates between 4,000 and 10,000 women and men, who tended to arrive mainly during the Christian pilgrimage period, between October and May.

        In order to ensure autonomous and systematic provision of water for the thousands of pilgrims that annually reached the city the visionaries of IOPS inaugurated another ambitious project; its goal was to achieve full autonomy concerning the water consumption of the whole Moscow Square, with its numerous hostels. The way? Digging a system of water pits and pools in a scale unseen before in Jerusalem.

        The water supply system was erected next to the womens’ hostel named after Maria Alexandrovna in the Moscow Square complex. Open drainage pipes navigated water to open pools, to be used for consumption by beasts and farming. 

        In addition, two large water pits were quarried, to which rainwater was navigated in closed pipes directly from the roofs of the buildings. The first pit was 23.9 meters in length, 12.6 meters in width and 7.8 meters in depth. The second pit was dug on the mountainhill and its length was 18.3 meters, its width 12.7 meters and its depth 6.8 meters.
        The water from these two pits permitted all the Russian delegations and representations in the city to be autonomous as far as water supply is concerned.
        The pilgrims, the laundry facility, the bath house, the water boiler, the kitchen, the hospital – all these were able to enjoy uninterrupted water supply indubitably.

        In addition to the water pits, the Society (IOPS) dug over 2 kilometers of drainage pipelines in order to provide waste treatment coming from the Moscow Square complex.
        
        <b>A short story from the Arab-Israeli War (1948)</b>
        
        During the blockades on Jerusalem, there were approxiamately one thousand water pits that contained almost one million cubes of water. Consequently, the water harvested in the pits could satisfy the needs of the whole city of Jerusalem during the month-long blockade.

        The water stored in the pits indeed provided enough water to fill the needs of the city’s residents, but they gradually got exhausted. No man knew for how long the blockade would continue and when the pipeline leading water to the city would get repaired, after it had been blasted.
        
        As a consequence, every family received very little water, which they were asked to store and save the longest possible. How much is “little water”? - Prior to the blockade a family would use on average around a hundred liters of water daily, while in the time of the blockade each family was rationed ten liters daily – just a tenth of the regular quantity! Needless to say, this minuscule quantity of water forced the people of Jerusalem to meticulously plan their water consumption according to the rations.

        The Jerusalem-based “The Hebrew Radio” station would broadcast, every day anew, instructions and recommendations to the city’s residents on ways of using water cleverly and frugally. For instance: 1. The same water is to be used for cooking, laundry, floor mopping and latrine rinsing (w.c.). 2. Bowls are to be placed below each person taking a shower using the water at a low current. The collected water in the bowl is to be kept. 3. Dirty and used water is to be filtered in order to be reused for different needs. 4. Especially dirty water is to be reused just for the latrine.

        As previously mentioned, after a month the city of Jerusalem was drying up and by that point all the IDF was engaged in operation “Shiloach”, whose goal was digging a canal that would navigate water from a well in the city of Rechovot to Jerusalem passing solely from Hebrew settlemments. The operation was crowned with success and the city of Jerusalem was saved from drought.        
        `,
    og: `During 1858, as the construction works commenced in the land plot that Tsar Alexander II recently purchased just outside the city walls next to Jaffa Gate (known as Moscow Square), a fascinating discovery of an enormous stone pillar is made.
        
        The length of the pillar is 12 meters, its diameter 1.75 meters and its weight approximately 60 tons. The big column is made of the so-called “Jewish stone” (Hebrew: mizit yehudit, Arabic: mizzi yahudi), a specific variety of the world-renowned Jerusalem stone; a dark grey or yellow crystalline dolomite or dolomitic limestone, appreciated for its hardness which made it an excellent building material for the city of Jerusalem and its surroundings. Varieties of the Jerusalem stone have been used in numerous famous constructions in the area of Jerusalem, such as the Western Wall.

        Because of its size, the column is attributed to the Herodian period, which constitutes the epax of building activity in the land of Israel and Yehuda. Archaeologists estimate that the unearthed pillar was intended for the construction of the Second Temple relying on Yosef ben Matityahu’s (Flavius Josephus) testimony; he mentions huge columns “27-feet high” (aprox. 8.25 meters) being used for the construction of the Second Temple on Temple Mount. Other experts claim it to be impossible that this column was used for the construction of the Second Temple, as it is larger than 27 feet along with the fact that in the Herodian period it was customary to build using columns created of multiple sections of stone in contrast to this monolithic one.

        Since its discovery and because of its size, the pillar has been known as the “Finger of Og” among Jerusalem’s residents in the name of Og, king of Bashan, who is described in the Bible as a person of great size. According to a Talmudic text he was the only person to survive the Great Flood apart from Noah.
        `,
  },
  famousInfo: {
    raspotin: `One of the most interesting figures of modern history. Rasputin was a mystic and thought of himself as a holy person. He was described by people as a “stranik”, a word used to describe a pilgrim or a nomad in Russian culture, a wandering person traveling in an attempt to achieve a specific goal.

        His personal charm bought him a name in Saint-Peterburg’s high society in the beginning of the 20th century. In 1905 Rasputin made the acquaintance of Tsar Nikolai II for the first time. Tsar Nikolai and the Tsarina Alexandra Feodorovna were desperate to find a cure for their son and heir to the throne, who was suffering from hemophilia, and they chose to take a chance with Gregory Rasputin. Rasputin served as some sort of “healer” for Alexander and thus he earned the royal couple’s fondness and estimation, which in turn granted him indescribable power and influence.
        Rasputin’s influence on the royal court had grown so strong, that under his influence senior government officials were nominated and discharged.
        
        The esteemed status he enjoyed from the Tsars created also enemies for him. His enemies tried to revile him in front of the Tsar and Tsarina. Rasputin, a lover of drinking and debauchery, was photographed during one of his feasts by a photographer that ambushed him. The photographic material was so embarrassing for him that Tsar Nikolai II assigned him to perform the pilgrimage journey to the holy sites of Christianity in Jerusalem and purify himself. Rasputin was left with no other choice, and so in the Easter holiday, in March 1911, Gregory Rasputin visited the Holy Land.

        His pilgrimage journey began at Odessa, passed through the “Holy Mount” - Mount Athos – in Greece, through Turkey, Rhodes and Lebanon in order to arrive to the Land of Israel. He anchored in the beach of Jaffa, went up to Jerusalem, visited the holy sites of Christianity and, as usual, he incited a big commotion. In Jerusalem he was hosted in Sergey’s Courtyard and visited the Russian Orthodox churches and monasteries in Bethlehem, Hebron and the church of the Holy Sepulchre. He participated in the Easter festivities, and upon his sinful ways came the agonies of remorse, which caused him to worry of losing his special powers that granted him influence over Russian nobility. During his visit to the church in Gesthemane, he went out to the garden, and there he was struck by a moment of epiphany and revelation so powerful that he lost conscience for a long period of time. People from the church moved him to the hostel in the Russian Compound. After he recovered and gained his senses, Rasputin felt that God had forgiven him and decided to return to Saint-Peterburg.

        Historians believe that Rasputin’s influence on Tsar Nikolai II was very destructive causing defeats in the battlefield during WWI and eventually the downfall of the Romanov dynasty after 300 consecutive years of ruling the Russian Empire.
        
        Rasputin was eventually murdered by several members of Russian nobility in 1916 in order to eliminate his influence on the royal family, even though it did not prevent the revolution that terminated the Tsarist rule in Russia.  
        `,
    rapin: `Painter and sculptor of Ukrainian origin, one of the most popular Russian painters of his period. He became known for his realist style that greatly inspired painters during the first years of the Soviet Union and the style of socialist realism that developed in Russia at the time.
        
        Repin was member of the Itinerants’ Society, a group of artists that protested the academic formalities and restrictions in art. Repin has created some very inspirational pieces that represent the simple folk and the hierarchical society that ruled the world based on violence during the previous centuries.
        
        Repin was a portraitist of very rare talent and, among others, he painted Leo Tolstoy, Alexander Pushkin and the scientist Dmitry Mendeleev. In 1898 Repin journeyed to Jerusalem, where he completed his creation “Bearing of the Cross” that is exhibited in the Holy Trinity Cathedral.

        Repin described the emotions he felt in his journey in Jerusalem in the following words: “In the entire city of Jerusalem there is something so touching that makes you weep, something like no other anywhere in the world. There are no words to express the feelings, in every place there is a spirit of eternity”.(1844 – 1930).
        `,
    koslev: `Russian painter and illustrator. Koshelev was an expert in painting scenes depicting everyday life and religious motifs. Koshelev’s paintings commemorate a number of principal churches in Russia such as the “Cathedral of Jesus the Savior” in Moscow, one of the most noteworthy churches in Russia, and the “Cathedral of St. Isaac from Dalmatia”. As a consequence of all his work, Koleshev received the title of Professor in the Imperial Academy of Art in Saint-Peterburg. A collection of his works titled “The way of the Cross” is exhibited in the Holy Trinity Cathedral in the old city of Jerusalem.(1840 – 1918).

        `,
    pandov: `Art historian with special expertise in Russian Christian icons. He taught in Novgorod and Saint-Peterburg universities and was a member of the Russian Classical Arts Academy.(1844 – 1925).
        `,
    warship: `In 1899 the warship “Alexander II” anchored in the port of Jaffa and on it 30 officers and 600 sailors. The Society hosted the entire crew at Sergey’s Courtyard, organized visits to the Society’s schools for the sailors, took them to excursions to the holy sites in Palestine and even arranged for them to receive blessings from the people of the Ecclesiastical Mission in Jerusalem.
        
        The Admiral of the warship carried out a tour of the warship for the pupils of the Society’s schools. Furthermore, the crews of the ships “Zabyaka” and “Kostroma” paid Sergey’s Courtyard a visit.
        `,
    baily: `Author, poet, theorist and literary critic known by the nome-de-plum Andrei Bely, one of the prominent figures in the symbolist movement in Russian literature. His novel “Peterburg” was commented by Vladimir Nabokov as one of the four greatest novels of the 20th century.(1880-1934).
        `,
    arseny: `Arseniy Stadnitski was a priest and rector of the Theological Academy of Moscow who led a mission of professors and students to the Holy Land in 1900. Another priest known by the name Kirilovsky also joined the mission. The endeavor was crowned a success and was documented in a special text by Alyona Strelnikova. 
         
         Later in his life, Stadnitski became a bishop, member of the governmental council of Tsarist Russia, Metropolite of Tashkent and Turkistan and member of Russia’s Holy Synod. 
         
         Kirilovsky was a murdered a year after he became a bishop, together with a nun and five innocent people, during the days of "red terror". After many years Kirilovsky was made a saint by the Russian Church.(1862 – 1936).
       `,
  },
  famousTitles: {
    raspotin: "Gregory Yefimovich Rasputin",
    rapin: "Ilya Yefimovich Repin",
    koslev: "Nikolai Andreyevich Koshelev",
    pandov: "Nikodim Pavlovich Kondakov",
    warship: "Warship “Alexander II” Crew",
    baily: "Boris Nikolayevich Bugaev",
    arseny: "The Academic Mission",
  },
};
export { englishText as default };
